ganglia/ganglia-web

api/search.php
`/lib/functions.php` was moved to `/functions.php` for quite a while.
This PR uses the new path for `/api/search.php` to include it.
=> Use the new path for functions.php

cluster_view.php
If case_sensitive_hostnames is set to false, lowercase the hostname for $host_url or else the graphs will not draw.
=> Case-Sensitivity fix for hostnames and cluster_view

aggregate_graphs.php, conf_default.php.in, templates/default/header.tpl
Improve user experience for selecting metrics as part of building aggregate graphs. You can now either select metrics from a dropdown list, or type metric regular expressions. The regular expression is completed by typing one of: <cr>, ',', or ' '.
Minor refactoring of code associated with drag-selecting a custom time range in header.tpl to align with future changes. No change in functionality intended.
=> Improve user experience for selecting metrics in aggregate graphs

graph.php
Apache error log was reporting _ERROR: xport: invalid option -- 't'_. Also, both CVS and JSON exports were empty.
I'm pretty sure that the '-t' option was just a typo from the code cleanup in 1de9cf2a2875edc0266a9a01a52ccc3d96bdd2b6
=> Remove invalid rrdtool option (-t).

graph.d/cpu_report.php, graph.d/mem_report.php, header.php
The 'Choose a Source' button was listing the current Grid. This returns the behavior back to before 2164f3fb3b3a77f2501627400d406dffdcb9578, where the current Grid was not shown in the list. This also fixes the problem that 2164f3fb3b3a77f2501627400d406dffdcb9578 was attempting to address, where a cluster with the same name as a grid would get filtered out. 
The logic of 2164f3fb3b3a77f2501627400d406dffdcb9578 was flawed because $context is always "meta" at that point, making the _if_ statement always false.
Now it checks if the name is the same as the current grid and if it is a grid, is so, then skip it.
=> Do not show current Grid in 'Choose a Source.'

Makefile
Some distros (e.g. SuSE) have a group name which differs from the Apache user name
=> Add APACHE_GROUP as user configurable

actions.php, graph.php, graph_all_periods.php, inspect_graph.php, js/ganglia.js, templates/default/graph_all_periods.tpl, templates/default/header.tpl, templates/default/views_view.tpl
Improvements to the dialog content for adding items to views. For example, only display warning/critical fields for metric graphs.
Inspect-graph. Auto-size the multi-select legend box.
Inspect-graph. Remove any residual content from the graph popup that may have been left over from viewing a trend plot.
Cosmetic changes to the used to organize views (if that option is selected).
Change the title of the popup used to add an item to a view. Added missing &s to several query strings.
Added the -t option to the rrdtool xport command. This is a requirement for rrdtool 1.6.0 to replicate the existing data format with a timestamp for each row.
Introduce some spacing between toolbar entries when wrapping occurs. 
Disable refresh of the search view.
Replace individual <script> statements with a …
=> Various maintenance tasks

conf_default.php.in, functions.php, graph.d/metric.php, header.php, js/flot_graph.js, js/ganglia.js, js/jquery.flot.events.js, templates/default/header.tpl, templates/default/host_view.tpl, templates/default/scripts.tpl, templates/default/view_content.tpl, view_content.php, views_view.php
- Converted inspect_graph.php into js/flot_graph.js which contains two classes FlotGraph and InspectGraph. InspectGraph is used to implement the current inspection functionality, and FlotGraph provides a reusable graph based on Flot that may be used for graph-engine = flot.
- Added a Clear button to the Inspect graph Line/Stack/Clear toolbar. This allows for rrdtool graphs that are a combination of stacks and lines to be rendered correctly. The cleared state is active by default.
- Improve performance of the host view by only refreshing graphs visible in the browser viewport. It is planned to make similar changes to other views.
- Fixed an issue where series in metric graphs were not labeled using the metric metric name which resulted in them not being correctly rendered when exported to …
=> Convert inspect_graph to JS class

conf_default.php.in, host_view.php
This is essentially a copy of pull request #254 by RyanFolsom. Since he hasn't responded for over a year I created my own clone and applied his fix (please let me know if this is not the usual procedure!):
From #254:
> The Problem
In the Web UI if a host goes down, many of the metrics become unavailable. These metrics can be extremely valuable in determining what went wrong. In some cases, these hosts may never come back (such as autoscaling groups through Amazon).
> The Change
Added a variable in the configuration file, $conf['show_host_data_if_down']. When false (default), the additional metrics do not render, and the behavior as it is today does not change. If set to true, the graphs and metrics will render under the host_view page, even if the host is down.
Especially when a node went …
=> Show data for down nodes

functions.php
We noted rrdtool crashing when an invalid clustername is passed to ganglia-web (e.g. ?c=not_our_cluster).  While the segfault is due to a bug we isolated in rrdtool when using the caching daemon, it seems appropriate for ganglia-web to check the "c" CGI parameter to ensure it's a defined cluster.  As it stands, this code change simply ensures the find_avg() function doesn't pass any non-existent files to rrdtool.  The check for a valid cluster name should probably be implemented at a higher level, though, which might make the existence of the directory/file a valid precondition to find_avg() and negate this patch.
=> find_avg:  check for existence of rrd file before exec'ing rrdtool

host_view.php
Useful for showing for instance the new disk_report, that is more interesting on a host-by-host basis.
=> Allow adding default graphs on host view only

cluster_view.php
The number of rows equals the number of columns in the heatmap. However, it can happen, that the entire last row is unused ( plus some squares of the second last row). In that case, the heatmap was wrong, as the last row was omitted and the second last got more entries than there are columns which led to a false rendering of the map...
=> Fix for the heatmap in cluster_view,

conf_default.php.in, graph.d/mem_report.php
Previously the Slab memory (for Linux only) was included
in "use/share" (blue) rather than "cache/buffer" (green).
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=565518
https://github.com/ganglia/monitor-core/pull/297
=> If mem_slab is available, improve the mem_report

host_view.php
In 52f72b961b80e6e47a18b34af8601aeacaf3c534 getOptionalReports() was refactored not to use global $conf_dir variable but instead pass needed variables as parameters. This broke another change, 0888f0195507a5557a8a5656be586505a38a983a, thas was merged the same day.
=> Fix incorrect conf_dir variable

graph.d/mem_report.php
When introducing the new values for "slab",
there is period when old values are missing...
Make sure to count those as zero properly,
so that the total amount of memory lines up
----
Sorry @vvuksan - same as in 6d6195f571402413d5df747e37330b2cba6077f4
=> Cope with mem RRD missing cached/slab/buffers

templates/default/cluster_host_metric_graphs.tpl
Starting from PHP7 selecting 0 columns (metric + report) throws exception after printing first host.
=> Fix "Uncaught DivisionByZeroError: Modulo by zero"

functions.php
PHP 7.1 introduces a fatal error when you call a method with not enough arguments (https://www.php.net/manual/en/migration71.incompatible.php)
Sample error you'd see:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function build_aggregate_graph_config(), 4 passed in /home/ganglia-webfrontend/decompose_graph.php on line 40 and exactly 6 expected in /home/ganglia-webfrontend/functions.php:1156
```
Based off decompose's usage, these arguments were always intended to be optional (especially since we run `isset()` later), thus I recommend making them optional.
=> Add default arguments so decompose works on php7.1

conf_default.php.in, graph.d/mem_report.php
Newer Linux kernels (3.14 and some backports) have a MemAvailable field
that provides a more accurate estimate of memory available to userspace.
Show this metric (if present), since not all of Cached and Slab can be
used or reclaimed - which makes our (guess of) "Use" to be inaccurate...
Needs PR https://github.com/ganglia/monitor-core/pull/300 (for the metric)
=> Add the available memory to the graph, if present

cluster_view.php
Whereas heatmap coloring is different than node background, this modification do apply scaling on it so heatmap behave alike
=> Scaling heatmap

nagios/check_heartbeat.php
Hi.
I have problems with hostnames like n1 and n10 when using checkheartbeat.
I add searching fqdn by full compare and if it doesn't find any exact name, i'm using strpos in addition.
=> add searching fqdn by full string compare not only by substring

api/host.php
In c5e5831d23c6db0b04a868578680b32cb03ee952 an attempt was made to replace the deprecated `split` function for PHP 7.0. However, `str_split` was not the correct replacement for the task. `explode` is the function that needs to be used here.
=> Replace str_split with explode

graph.php
We have pool CPU reports for Power systems in json format with metrics like these:
"series" : [
{ "hostname": "host1", "clustername": "C1", "metric": "cpu_used", "color": "00ff00", "label": "host1", "type": "stack" },
{ "hostname": "host2", "clustername": "C1", "metric": "cpu_used", "color": "0000ff", "label": "host2", "type": "stack" },
...
{ "hostname": "host1", "clustername": "C1", "metric": "cpu_in_pool", "color": "000000", "label": "CPU in Pool", "line_width": "2", "type": "line" }
]
Expected outcome is that each area represents the CPU usage of an LPAR.
The reports displayed the same CPU used values for all LPARs instead and no
correlation to the single LPAR.
When calling graph.php with the option "&debug=3" we saw in the rrdtool command: …
=> Fix json reports in cluster context using host metrics

Makefile
Current release is 3.7.5, but the web interface displays 3.7.4.
Is there a "release checklist"? This has been forgotten in the past...
=> Web-Interface still displays version 3.7.4

cluster_view.php
When displaying a cluster view I get this message in apache's error.log:
reports = Array\n(\n    [load_report] => load_one\n    [cpu_report] => 1\n
[mem_report] => 1\n    [network_report] => 1\n    [packet_report] => 1\n)\n
For me it looks like a trace - lets remove it.
=> Remove error_log() call which is trace from cluster_view.php

lib/common_api.php
According to the php documentation the "context" parameter to the
error handler has been deprecated:
https://www.php.net/manual/en/function.set-error-handler.php
Let's move on and get ready for a newer php version (debian bullseye has 7.4).
This in one small step to get ready for php8. See https://github.com/ganglia/ganglia-web/issues/361
=> Update error handler for php 7.2
